Repository Wayble-Project/wayble-spring, pull requests merged in 2025-08, with the labels that each got.

#91 [feat] CORS 구현 완료
  src/main/java/com/wayble/server/common/config/SecurityConfig.java
Labels: 💡 feature

#93 [refactor] 유저 장애유형,이동보조수단 enum 처리 및 유저 이미지 등록 관련 로직 주석 처리
  src/main/java/com/wayble/server/user/dto/UserInfoRegisterRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserInfoResponseDto.java
  src/main/java/com/wayble/server/user/dto/UserInfoUpdateRequestDto.java
  src/main/java/com/wayble/server/user/entity/DisabilityType.java
  src/main/java/com/wayble/server/user/entity/MobilityAid.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/service/UserInfoService.java
Labels: 🔧 refactor, 🛠️ fix

#103 [feat] Discord Webhook 에러 알림 기능 구현
  .github/workflows/cd-develop.yml
  src/main/java/com/wayble/server/common/dto/DiscordWebhookPayload.java
  src/main/java/com/wayble/server/common/exception/GlobalExceptionHandler.java
Labels: 💡 feature

#104 [fix] 배포 서버에서 로그인,유저 정보 조회 관련 에러 해결
  .github/workflows/cd-develop.yml
  src/main/java/com/wayble/server/auth/entity/RefreshToken.java
  src/main/java/com/wayble/server/user/service/UserInfoService.java
Labels: 🐛 bug fix, 🛠️ fix

#113 [feat] 파일 업로드 기능 개선 및 API 구현, 관리자 페이지 웨이블존 이미지 등록&수정 기능 구현
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/admin/service/AdminWaybleZoneService.java
  src/main/java/com/wayble/server/aws/AmazonS3Manager.java
  src/main/java/com/wayble/server/aws/AwsErrorCase.java
  src/main/java/com/wayble/server/aws/controller/FileUploadController.java
  src/main/java/com/wayble/server/common/config/SecurityConfig.java
  src/main/java/com/wayble/server/direction/exception/DirectionErrorCase.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZone.java
  src/main/resources/templates/admin/wayblezone/wayble-zone-create.html
  src/main/resources/templates/admin/wayblezone/wayble-zone-detail.html
  src/main/resources/templates/admin/wayblezone/wayble-zone-edit.html
Labels: 💡 feature

#115 [fix] 배포 서버에서 유저 정보 수정 (PATCH) 관련 오류 해결
  src/main/java/com/wayble/server/common/config/SecurityConfig.java
Labels: 🐛 bug fix, 🛠️ fix

#126 [REFACTOR] 웨이블존 추천 경로 리팩토링
  src/main/java/com/wayble/server/direction/init/GraphInit.java
  src/main/java/com/wayble/server/direction/service/WaybleDijkstraService.java
  src/main/resources/wayble_markers.json
  src/test/java/com/wayble/server/direction/service/WalkingServiceTest.java
Labels: 🐛 bug fix, 🔧 refactor

#137 [FEAT] 길찾기 중 추가적인 정보 반영
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/common/config/HttpClientConfig.java
  src/main/java/com/wayble/server/direction/controller/TransportationController.java
  src/main/java/com/wayble/server/direction/dto/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/dto/request/TransportationRequestDto.java
  src/main/java/com/wayble/server/direction/dto/response/BusInfo.java
  src/main/java/com/wayble/server/direction/dto/response/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/external/opendata/OpenDataProperties.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/Arrival.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/OpenDataResponse.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/StationSearchResponse.java
  src/main/java/com/wayble/server/direction/repository/RouteRepository.java
  src/main/java/com/wayble/server/direction/service/BusInfoService.java
  src/main/java/com/wayble/server/direction/service/FacilityService.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
Labels: 💡 feature

#140 [FIX] 대중교통 길찾기의 환승 방식 조정
  src/main/java/com/wayble/server/direction/dto/TransportationGraphDto.java
  src/main/java/com/wayble/server/direction/entity/transportation/Edge.java
  src/main/java/com/wayble/server/direction/entity/transportation/Facility.java
  src/main/java/com/wayble/server/direction/entity/transportation/Node.java
  src/main/java/com/wayble/server/direction/repository/EdgeRepository.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
Labels: 🛠️ fix

#141 [release] 진행상황 Main 브랜치에 반영
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/common/config/HttpClientConfig.java
  src/main/java/com/wayble/server/direction/controller/TransportationController.java
  src/main/java/com/wayble/server/direction/dto/TransportationGraphDto.java
  src/main/java/com/wayble/server/direction/dto/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/dto/request/TransportationRequestDto.java
  src/main/java/com/wayble/server/direction/dto/response/BusInfo.java
  src/main/java/com/wayble/server/direction/dto/response/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/entity/transportation/Edge.java
  src/main/java/com/wayble/server/direction/entity/transportation/Facility.java
  src/main/java/com/wayble/server/direction/entity/transportation/Node.java
  src/main/java/com/wayble/server/direction/external/opendata/OpenDataProperties.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/Arrival.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/OpenDataResponse.java
  src/main/java/com/wayble/server/direction/external/opendata/dto/StationSearchResponse.java
  src/main/java/com/wayble/server/direction/repository/EdgeRepository.java
  src/main/java/com/wayble/server/direction/repository/RouteRepository.java
  src/main/java/com/wayble/server/direction/service/BusInfoService.java
  src/main/java/com/wayble/server/direction/service/FacilityService.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
Labels: release

#136 [feat] 가게가 웨이블존인지 여부를 판단하는 기능 구현
  src/main/java/com/wayble/server/explore/controller/WaybleZoneSearchController.java
  src/main/java/com/wayble/server/explore/dto/search/request/WaybleZoneSearchConditionDto.java
  src/main/java/com/wayble/server/explore/repository/search/WaybleZoneQuerySearchRepository.java
  src/main/java/com/wayble/server/explore/service/WaybleZoneSearchService.java
  src/test/java/com/wayble/server/explore/WaybleZoneSearchApiIntegrationTest.java
Labels: 💡 feature

#144 [release] 진행상황 main 브랜치에 반영
  src/main/java/com/wayble/server/direction/dto/response/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
  src/main/java/com/wayble/server/explore/controller/WaybleZoneSearchController.java
  src/main/java/com/wayble/server/explore/dto/search/request/WaybleZoneSearchConditionDto.java
  src/main/java/com/wayble/server/explore/repository/search/WaybleZoneQuerySearchRepository.java
  src/main/java/com/wayble/server/explore/service/WaybleZoneSearchService.java
  src/test/java/com/wayble/server/explore/WaybleZoneSearchApiIntegrationTest.java
Labels: release

#146 [feat] 공덕 지역 웨이블존 데이터 추가
  src/main/java/com/wayble/server/admin/controller/wayblezone/AdminWaybleZoneViewController.java
  src/main/java/com/wayble/server/admin/dto/wayblezone/AdminWaybleZoneNavigationDto.java
  src/main/java/com/wayble/server/admin/repository/AdminWaybleZoneRepositoryCustom.java
  src/main/java/com/wayble/server/admin/repository/AdminWaybleZoneRepositoryImpl.java
  src/main/java/com/wayble/server/admin/service/AdminWaybleZoneService.java
  src/main/java/com/wayble/server/wayblezone/importer/CsvSupport.java
  src/main/resources/data/gongduck_wayblezone.csv
  src/main/resources/templates/admin/wayblezone/wayble-zone-detail.html
Labels: 💡 feature

#154 [REFACTOR] 유저 장소 저장 관련 api 개선 및 리뷰 등록 칼럼 변경
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/review/dto/ReviewRegisterDto.java
  src/main/java/com/wayble/server/review/service/ReviewService.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRemoveRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceSummaryDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceZonesResponseDto.java
  src/main/java/com/wayble/server/user/entity/UserPlace.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/repository/UserPlaceRepository.java
  src/main/java/com/wayble/server/user/repository/UserPlaceWaybleZoneMappingRepository.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZone.java
Labels: 🔧 refactor, 🛠️ fix

#157 [release] 진행상황 Main 브랜치에 반영
  src/main/java/com/wayble/server/direction/service/WaybleDijkstraService.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/review/dto/ReviewRegisterDto.java
  src/main/java/com/wayble/server/review/service/ReviewService.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRemoveRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceSummaryDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceZonesResponseDto.java
  src/main/java/com/wayble/server/user/entity/UserPlace.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/repository/UserPlaceRepository.java
  src/main/java/com/wayble/server/user/repository/UserPlaceWaybleZoneMappingRepository.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZone.java
  src/main/resources/wayble_markers.json
Labels: release

#161 [refactor] 웨이블존 상세 조회에 위도,경도 추가 + 토큰 관련 리팩토링 + 웨이블존 목록 조회, 리뷰 작성 테스트 코드 작성
  src/main/java/com/wayble/server/auth/resolver/CurrentUser.java
  src/main/java/com/wayble/server/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/wayble/server/common/config/WebMvcConfig.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneDetailResponseDto.java
  src/main/java/com/wayble/server/wayblezone/service/WaybleZoneService.java
  src/test/java/com/wayble/server/review/service/ReviewServiceTest.java
  src/test/java/com/wayble/server/wayblezone/controller/WaybleZoneControllerTest.java
Labels: 💡 feature, 🔧 refactor, 🤔 test

#166 [FEAT] 지하철의 승강기 정보 출력
  src/main/java/com/wayble/server/direction/dto/response/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/entity/transportation/Edge.java
  src/main/java/com/wayble/server/direction/entity/transportation/Elevator.java
  src/main/java/com/wayble/server/direction/entity/transportation/Node.java
  src/main/java/com/wayble/server/direction/entity/transportation/Route.java
  src/main/java/com/wayble/server/direction/entity/type/DirectionType.java
  src/main/java/com/wayble/server/direction/repository/ElevatorRepository.java
  src/main/java/com/wayble/server/direction/service/FacilityService.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
Labels: 💡 feature

#169 [refactor] 리졸버 로직 개선, swagger에서 userId 필수 파라미터 입력인곳 제거
  src/main/java/com/wayble/server/auth/exception/AuthErrorCase.java
  src/main/java/com/wayble/server/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/test/java/com/wayble/server/review/service/ReviewServiceTest.java
Labels: 🔧 refactor, 🤔 test

#171 [fix] 유저 웨이블존 저장 및 조회 관련 API 수정
  src/main/java/com/wayble/server/auth/exception/AuthErrorCase.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceAddZonesRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceCreateRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceCreateResponseDto.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
Labels: 💡 feature, 🛠️ fix

#172 [fix] 페이징 관련 오프바이원 버그 수정 + 페이징 제약 및 검증 로직 개선
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
Labels: 🐛 bug fix, 🔧 refactor

#173 [fix] 하나의 웨이블존에 여러개의 저장한 리스트를 추가할 수 있도록 로직 변경
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceAddZonesRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserResponseDto.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
Labels: 🔧 refactor, 🛠️ fix

#168 [release] 진행 상황을 main으로 머지
  src/main/java/com/wayble/server/auth/exception/AuthErrorCase.java
  src/main/java/com/wayble/server/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/wayble/server/direction/dto/response/TransportationResponseDto.java
  src/main/java/com/wayble/server/direction/entity/transportation/Edge.java
  src/main/java/com/wayble/server/direction/entity/transportation/Elevator.java
  src/main/java/com/wayble/server/direction/entity/transportation/Node.java
  src/main/java/com/wayble/server/direction/entity/transportation/Route.java
  src/main/java/com/wayble/server/direction/entity/type/DirectionType.java
  src/main/java/com/wayble/server/direction/repository/ElevatorRepository.java
  src/main/java/com/wayble/server/direction/service/FacilityService.java
  src/main/java/com/wayble/server/direction/service/TransportationService.java
  src/main/java/com/wayble/server/explore/repository/search/WaybleZoneQuerySearchRepository.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceAddZonesRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceCreateRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceCreateResponseDto.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserResponseDto.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
  src/test/java/com/wayble/server/explore/WaybleZoneSearchApiIntegrationTest.java
  src/test/java/com/wayble/server/review/service/ReviewServiceTest.java
Labels: release

#178 [Hot fix] 웨이블존 상세 정보 대표 이미지 조회 오류 해결
  src/main/java/com/wayble/server/explore/service/WaybleFacilityDocumentService.java
  src/main/java/com/wayble/server/explore/service/WaybleZoneRecommendService.java
  src/main/java/com/wayble/server/explore/service/WaybleZoneSearchService.java
  src/main/java/com/wayble/server/wayblezone/service/WaybleZoneService.java
Labels: 🐛 bug fix
