Repository Wayble-Project/wayble-spring, pull requests merged in 2025-07, with the labels that each got.

#10 [feat] 도메인 별 기본 클래스 구현 완료
  build.gradle
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/common/entity/Address.java
  src/main/java/com/wayble/server/common/entity/BaseEntity.java
  src/main/java/com/wayble/server/direction/controller/DirectionController.java
  src/main/java/com/wayble/server/direction/exception/DirectionErrorCase.java
  src/main/java/com/wayble/server/direction/service/DirectionService.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/review/dto/ReviewRegisterDto.java
  src/main/java/com/wayble/server/review/dto/ReviewResponseDto.java
  src/main/java/com/wayble/server/review/entity/Review.java
  src/main/java/com/wayble/server/review/entity/ReviewImage.java
  src/main/java/com/wayble/server/review/exception/ReviewErrorCase.java
  src/main/java/com/wayble/server/review/repository/ReviewImageRepository.java
  src/main/java/com/wayble/server/review/repository/ReviewRepository.java
  src/main/java/com/wayble/server/review/service/ReviewService.java
  src/main/java/com/wayble/server/search/controller/SearchController.java
  src/main/java/com/wayble/server/search/exception/SearchErrorCase.java
  src/main/java/com/wayble/server/search/service/SearchService.java
  src/main/java/com/wayble/server/user/controller/UserController.java
  src/main/java/com/wayble/server/user/dto/UserRegisterDto.java
  src/main/java/com/wayble/server/user/dto/UserResponseDto.java
  src/main/java/com/wayble/server/user/entity/Gender.java
  src/main/java/com/wayble/server/user/entity/LoginType.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/entity/UserType.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/repository/UserRepository.java
  src/main/java/com/wayble/server/user/service/UserService.java
  src/main/java/com/wayble/server/wayblezone/controller/WaybleZoneController.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneRegisterDto.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneResponseDto.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZone.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZoneImage.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZoneType.java
  src/main/java/com/wayble/server/wayblezone/exception/WaybleZoneErrorCase.java
  src/main/java/com/wayble/server/wayblezone/repository/WaybleZoneImageRepository.java
  src/main/java/com/wayble/server/wayblezone/repository/WaybleZoneRepository.java
  src/main/java/com/wayble/server/wayblezone/service/WaybleZoneService.java
Labels: 💡 feature

#16 [CI] 워크플로우 수정
  .github/workflows/cd-develop.yml
Labels: 💡 feature

#12 [feat] 웨이블존 리뷰 작성 API 구현 및 Swagger 세팅
  build.gradle
  src/main/java/com/wayble/server/common/swagger/ErrorResponseDoc.java
  src/main/java/com/wayble/server/config/SwaggerConfig.java
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/review/dto/ReviewRegisterDto.java
  src/main/java/com/wayble/server/review/entity/Review.java
  src/main/java/com/wayble/server/review/entity/ReviewImage.java
  src/main/java/com/wayble/server/review/service/ReviewService.java
Labels: 💡 feature, ⚙️ chore, 🔧 refactor

#31 [feat] 웨이블존 목록 조회 API 구현
  src/main/java/com/wayble/server/common/entity/Address.java
  src/main/java/com/wayble/server/wayblezone/controller/WaybleZoneController.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneListResponseDto.java
  src/main/java/com/wayble/server/wayblezone/exception/WaybleZoneErrorCase.java
  src/main/java/com/wayble/server/wayblezone/repository/WaybleZoneRepository.java
  src/main/java/com/wayble/server/wayblezone/service/WaybleZoneService.java
Labels: 💡 feature, 🔧 refactor

#33 [feat] 웨이블존 상세 조회 API 구현
  src/main/java/com/wayble/server/common/dto/FacilityDto.java
  src/main/java/com/wayble/server/wayblezone/controller/WaybleZoneController.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneDetailResponseDto.java
  src/main/java/com/wayble/server/wayblezone/dto/WaybleZoneListResponseDto.java
  src/main/java/com/wayble/server/wayblezone/service/WaybleZoneService.java
Labels: 💡 feature, 🔧 refactor, 🛠️ fix

#39 [feat] 유저 장소 저장 api 구현 (충돌 해결용)
  src/main/java/com/wayble/server/review/controller/ReviewController.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceRequestDto.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/repository/UserPlaceRepository.java
  src/main/java/com/wayble/server/user/repository/UserPlaceWaybleZoneMappingRepository.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
Labels: 💡 feature

#43 [refactor] 유저 엔티티 연관관계 정의 및 회원가입용 DTO 구현
  src/main/java/com/wayble/server/user/dto/UserRegisterDto.java
  src/main/java/com/wayble/server/user/dto/UserRegisterRequestDto.java
  src/main/java/com/wayble/server/user/entity/Disability.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/entity/UserDisabilityMapping.java
  src/main/java/com/wayble/server/user/repository/UserRepository.java
Labels: 💡 feature, 🔧 refactor

#44 [feat] JWT 기반 로그인, 회원가입 구현
  build.gradle
  src/main/java/com/wayble/server/common/config/SecurityConfig.java
  src/main/java/com/wayble/server/common/config/security/JwtProperties.java
  src/main/java/com/wayble/server/common/config/security/jwt/JwtAuthentication.java
  src/main/java/com/wayble/server/common/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wayble/server/common/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/wayble/server/user/controller/UserController.java
  src/main/java/com/wayble/server/user/dto/UserLoginRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserRegisterRequestDto.java
  src/main/java/com/wayble/server/user/dto/token/TokenResponseDto.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/UserService.java
  src/main/java/com/wayble/server/user/service/auth/AuthService.java
Labels: 💡 feature, ⚙️ chore, 🛠️ fix

#55 [feat] 내가 저정한 장소 목록 조회 API 구현
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/UserPlaceListResponseDto.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/repository/UserPlaceWaybleZoneMappingRepository.java
  src/main/java/com/wayble/server/user/service/UserPlaceService.java
Labels: 💡 feature, 🔧 refactor

#56 [FEAT] 도보 최적 경로 API
  build.gradle
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/common/config/WebClientConfig.java
  src/main/java/com/wayble/server/direction/controller/WalkingController.java
  src/main/java/com/wayble/server/direction/controller/swagger/WalkingSwagger.java
  src/main/java/com/wayble/server/direction/exception/WalkingErrorCase.java
  src/main/java/com/wayble/server/direction/external/tmap/TMapClient.java
  src/main/java/com/wayble/server/direction/external/tmap/TMapProperties.java
  src/main/java/com/wayble/server/direction/external/tmap/dto/request/TMapRequest.java
  src/main/java/com/wayble/server/direction/external/tmap/dto/response/TMapParsingResponse.java
  src/main/java/com/wayble/server/direction/external/tmap/dto/response/TMapResponse.java
  src/main/java/com/wayble/server/direction/external/tmap/mapper/TMapMapper.java
  src/main/java/com/wayble/server/direction/service/WalkingService.java
Labels: 💡 feature

#60 [feat] 카카오 소셜 로그인 구현
  src/main/java/com/wayble/server/user/controller/KakaoLoginController.java
  src/main/java/com/wayble/server/user/controller/UserPlaceController.java
  src/main/java/com/wayble/server/user/dto/KakaoUserInfoDto.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/auth/KakaoLoginService.java
Labels: 💡 feature

#67 [fix] elastic search CI/CD 배포 문제 해결
  .github/workflows/cd-develop.yml
  Dockerfile.elasticsearch
  docker-compose.yml
  src/main/java/com/wayble/server/common/config/ElasticsearchConfig.java
  src/main/java/com/wayble/server/explore/dto/search/WaybleZoneDistrictResponseDto.java
  src/main/java/com/wayble/server/explore/repository/search/WaybleZoneQuerySearchRepository.java
Labels: 🐛 bug fix, ⚙️ chore

#72 [feat] 유저 정보 등록 API 구현
  src/main/java/com/wayble/server/user/controller/UserController.java
  src/main/java/com/wayble/server/user/dto/UserInfoRegisterRequestDto.java
  src/main/java/com/wayble/server/user/dto/UserLoginRequestDto.java
  src/main/java/com/wayble/server/user/entity/User.java
  src/main/java/com/wayble/server/user/exception/UserErrorCase.java
  src/main/java/com/wayble/server/user/service/UserInfoService.java
Labels: 💡 feature, 🛠️ fix

#80 [feat] 웨이블존 MySQL<->Elastic Search 동기화 기능 구현 완료
  .github/workflows/cd-develop.yml
  src/main/java/com/wayble/server/ServerApplication.java
  src/main/java/com/wayble/server/explore/entity/WaybleZoneDocument.java
  src/main/java/com/wayble/server/review/service/ReviewService.java
  src/main/java/com/wayble/server/wayblezone/entity/WaybleZone.java
  src/main/java/com/wayble/server/wayblezone/repository/WaybleZoneRepositoryCustom.java
  src/main/java/com/wayble/server/wayblezone/repository/WaybleZoneRepositoryImpl.java
  src/main/java/com/wayble/server/wayblezone/sync/WaybleZoneSyncScheduler.java
  src/main/java/com/wayble/server/wayblezone/sync/WaybleZoneSyncService.java
Labels: 💡 feature

#82 [chore] Token 관련 로직을 Auth 폴더로 분리
  src/main/java/com/wayble/server/auth/controller/AuthController.java
  src/main/java/com/wayble/server/auth/dto/TokenResponseDto.java
  src/main/java/com/wayble/server/auth/enttiy/RefreshToken.java
  src/main/java/com/wayble/server/auth/repository/RefreshTokenRepository.java
  src/main/java/com/wayble/server/auth/service/AuthService.java
  src/main/java/com/wayble/server/auth/service/KakaoLoginService.java
  src/main/java/com/wayble/server/common/config/SecurityConfig.java
  src/main/java/com/wayble/server/user/controller/KakaoLoginController.java
  src/main/java/com/wayble/server/user/controller/UserController.java
Labels: ⚙️ chore
